name: finance_ai_app
description: "Ứng dụng quản lý tài chính cá nhân thông minh tích hợp AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  google_mlkit_text_recognition: ^0.16.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  permission_handler: ^11.3.1

  # Auth providers
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.2

  # UI / Charts
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.19.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.5
  percent_indicator: ^4.2.3
  path_provider: ^2.1.4

  # AI (Gemini)
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
