// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4Bedx0xkZ1lJ3YxEu7SWM5Ad6ovTGQ4',
    appId: '1:290574068185:web:840c2caeba9665b86711c8',
    messagingSenderId: '290574068185',
    projectId: 'finance-ai-app-6df28',
    authDomain: 'finance-ai-app-6df28.firebaseapp.com',
    storageBucket: 'finance-ai-app-6df28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauEJq_yx-se3xUrcO63HcTvwbKPQ8-w0',
    appId: '1:290574068185:android:aaa0364c13c5e4bc6711c8',
    messagingSenderId: '290574068185',
    projectId: 'finance-ai-app-6df28',
    storageBucket: 'finance-ai-app-6df28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIVZSyvHFjNgbD-k7sUAUuSEXxY_dMxM',
    appId: '1:290574068185:ios:8ae851e4e126a9e46711c8',
    messagingSenderId: '290574068185',
    projectId: 'finance-ai-app-6df28',
    storageBucket: 'finance-ai-app-6df28.firebasestorage.app',
    androidClientId: '290574068185-t6e8svaj58kh6hmjok1devdivpeciqhh.apps.googleusercontent.com',
    iosClientId: '290574068185-3oli8unhj8jktcqlgbg95nhc1chd0ghk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj4Bedx0xkZ1lJ3YxEu7SWM5Ad6ovTGQ4',
    appId: '1:290574068185:web:f1e2b7c8528f16f26711c8',
    messagingSenderId: '290574068185',
    projectId: 'finance-ai-app-6df28',
    authDomain: 'finance-ai-app-6df28.firebaseapp.com',
    storageBucket: 'finance-ai-app-6df28.firebasestorage.app',
  );
}
